name: unsplash_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  logger: ^2.5.0
  provider: ^6.1.2
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  flutter_blurhash: ^0.8.2
  flutter_styled_toast: ^2.2.1
  gap: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  retrofit_generator: ^9.1.5
  json_serializable: ^6.9.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/main_page/
